---
### Inputs:
- name: WAZUH CLIENT | Assert Inputs | get_alerts_by_agent_ip.yml
  ansible.builtin.assert:
    that:
      - (wazuh_client_indexer_base_url is defined) and (wazuh_client_manager_base_url | length > 0)
      - (wazuh_client_indexer_username is defined) and (wazuh_client_indexer_username | length > 0)
      - (wazuh_client_indexer_password is defined) and (wazuh_client_indexer_password | length > 0)
      - (wazuh_client_agent_ip is defined) and (wazuh_client_agent_ip | length > 0)

- name: Get Alerts of agent
  ansible.builtin.uri:
    url: "{{ wazuh_client_indexer_base_url }}/wazuh-alerts-*/_search?pretty"
    method: GET
    user: "{{ wazuh_client_indexer_username }}"
    password: "{{ wazuh_client_indexer_password }}"
    force_basic_auth: true
    validate_certs: false
    body_format: json
    body:
      query:
        bool:
          filter:
            - range:
                rule.level:
                  gte: 12
            - term:
                agent.ip: "{{ wazuh_client_agent_ip }}"
      sort:
        - timestamp:
            order: desc
    status_code: [200]
  register: get_alerts_response

### Outputs:
- name: WAZUH CLIENT | Set Alerts
  ansible.builtin.set_fact:
    wazuh_client_alerts: "{{ get_alerts_response.json }}"
